import * as Yup from "yup";
export const receiptRegisterDetailsSchema = Yup.object().shape({
  receipt_no: Yup.string().required("Receipt No is required"),
  ulb_id: Yup.number().required("Ulb is required"),
  primary_acc_code_id: Yup.number().required("Primary Acc Code  is required"),
  revenue_module_id: Yup.number().required("Revenue Module  is required"),
  paid_by: Yup.string().required("Paid By is required"),
  receipt_mode_id: Yup.number().required("Receipt Mode  is required"),
  receipt_date: Yup.string().required("Receipt Date is required"),
  cheque_or_draft_no: Yup.string(),
  bank_amount: Yup.number(),
  cash_amount: Yup.number(),
  bank_acc_no: Yup.string(),
  deposit_date: Yup.string(),
  realisation_date: Yup.string(),
  wheather_returned: Yup.string(),
  remarks: Yup.string().required("Remarks is required"),
  entered_by_id: Yup.string(),
  entered_by_print_name: Yup.string().required("Print Name is required"),
});
